[target.aarch64-linux-android]
dockerfile = "./Dockerfile"

[build.env]
passthrough = [
    "V8_FROM_SOURCE",
    "SCCACHE_ERROR_LOG",
    "SCCACHE_LOG",
    "SCCACHE_DIR",
    "SCCACHE_IDLE_TIMEOUT",
]
